server:
  port: 8081
spring:
  application:
    name: eureka-server-01
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/,http://localhost:8082/eureka/