server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://192.168.0.168:3306/rabbitmq_order
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  rabbitmq:
    username: liuyz
    password: 123456
    # 因为使用了集群，所以需要配置集群地址，多个地址使用英文逗号,隔开
    addresses: 192.168.141.168:5672
    virtual-host: /
    # 确认机制类型
    publisher-confirm-type: correlated
logging:
  level:
    root: debug